blank_issues_enabled: true
contact_links:
  - name: Chrome Web Store
    url: https://chromewebstore.google.com/detail/github-issue-notes/iodoilfmmpjkkcamhbmdjpbjecmgladm
    about: Leave a review on Chrome Web Store
